FROM gitpod/workspace-full

# Install custom tools, runtime, etc.
RUN sudo apt-get update && wget --content-disposition 'https://pm.puppet.com/cgi-bin/pdk_download.cgi?dist=ubuntu&rel=18.04&arch=amd64&ver=latest'

RUN sudo apt-get install -y pdk*.deb

